# --- background { } ---
blur_level=7

# brightness = 0.5 (dimmed) -> dim 0-100, higher = darker
dim_level=40

# --- fonts ---
font="Departure Mono Nerd Font"

# --- input-field { } ---
# outer_color = rgb(151515)
ring_color="e2f2ff"
ringvercolor="e2f2ff"
ringwrongcolor="73a2c7"

insidecolor="c8c8c8"
insidevercolor="c8c8c8"
insidewrongcolor="a4553f"

text_color="e2f2ff"

key_hl_color="c8c8c8"
bshl_color="c8c8c8"
separator_color="00000000"

login_text="psswd"
verif_text="pending"
wrong_text="no."

# --- label { text = %H:%M } ---
time_format="%H:%M"
time_font_size=72

# --- label { text = %A, %B %d } ---
date_format="%A, %B %d"
date_font_size=24

login_font_size=24
verif_font_size=24
wrong_font_size=24

# --- misc ---
greeter_text=""
show_failed_attempts=true
